# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/theyakka/goro
    steps:
      - checkout
      - run: go get -v -t -d ./...

  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/theyakka/goro
    steps:
      - run: go test -v -covermode=count -coverprofile=coverage.out ./...
    post:
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.out
